AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/IndentationWidth:
  Width: 4

Layout/HashAlignment:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Layout/LineLength:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false
