source "https://rubygems.org"

gem "rails", "~> 8.1.3", ">= 8.1.3.1"
gem "pg", "~> 1.6.3"

gem "bootsnap", require: false

gem "are_search", path: ".."
gem "conf_vars",  git: "https://github.com/PotaSmith/conf_vars.git", tag: "v0.1.1"

group :development, :test do
    gem "rspec-rails"
end
